version: 0.2

phases:
  install:
  
    commands:
        # install npm
        - pip install django
       
  build:
    commands:
        # run build script
        - pip install -r requirements.txt
     
artifacts:
  files:
    - '**/*'
